[package]
name = "Rust"
version = "0.1.0"
authors = ["joseinaranjo5"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
queues="1.0.2"
